### ISSUE TITLE
Instructions for mac only

### ISSUE THREAD

**Issue by kevfrost** [itsonlyjames/obsidian-quick-select#4]
Recommend you include CTRL+ number as alternative for Linux and Windows users?

**Comment by itsonlyjames** [comment]
I've not personally tested it on Windows or Linux.. what is the current combination of keys used? 

I can setup an option for either mod key (current) or control. Won't be an issue.

**Comment by itsonlyjames** [comment]
Implemented a setting as well as key press tester in [v1.1.4](https://github.com/itsonlyjames/obsidian-quick-select/releases/tag/1.1.4).
